### ISSUE TITLE
CORS mentions in overview are hopefully redundant?

### ISSUE THREAD

**Issue by annevk** [WICG/js-self-profiling#17]
If CORS is not correct the load should fail and there would be nothing to execute. Why is it mentioned here?

**Comment by acomminos** [comment]
As classic scripts don't ordinarily require CORS, we need to be explicit about this check being passed. Otherwise, we'd expose part of the contents of script in traces that wouldn't ordinarily be accessible for reading.

This part is inspired by the interaction of onerror with CORS (i.e. via the crossorigin attribute on script tags).

**Comment by annevk** [comment]
That's not really how it works though. I guess what you need to inspect is the muted errors flag or some such in that case.

**Comment by acomminos** [comment]
This should be resolved now that this check has been replaced with a dependency on COOP/COEP, closing. Thanks!
