### ISSUE TITLE
Cross-origin leakage

### ISSUE THREAD

**Issue by annevk** [WICG/js-self-profiling#38]
> The primary concern with profiling JavaScript running on an event loop shared by multiple browsing contexts is ensuring that stack frames from cross-origin browsing contexts and cross-origin opaque scripts are not leaked. The spec aims to mitigate this by requring cross-origin isolation, providing a mechanism for UAs to ensure that all executed code within an agent cluster is accessible by script. 

I don't really understand these statements. Cross-origin isolation ensures that the top-level document gets its own process and that resources embedded into that process have minimally consented to being there. In the worst case multiple origins will share a single process.

Assuming the worst case, is this feature equivalent to enabling timing attacks or would it actually expose more, being itself directly responsible for cross-origin leakage?

**Comment by acomminos** [comment]
Thanks for bringing this up Anne, this section is a bit of a word salad. Originally we used an incumbent context filtering approach to filter out frames from functions executed in other realms, which is where the first part of the section comes from. I'll clean this up.

> Assuming the worst case, is this feature equivalent to enabling timing attacks or would it actually expose more, being itself directly responsible for cross-origin leakage?

IIUC, I'm assuming by "cross-origin leakage" you're referring to ProfilerFrame objects capturing functions from cross-origin scripts (since with cross-origin isolation, we don't have to worry about leaking execution in cross-origin subframes).

These scripts are only present in the profiler trace if they're fetched via CORS, or are same-origin with the top-level document. That shouldn't expose any new sources of cross-origin leakage, since the contents of these scripts are otherwise accessible. If a site really wanted to, they could fetch the script with an XHR and inject instrumentation similar to the [polyfill section of the TPAC 2018 slides](https://github.com/WICG/js-self-profiling/blob/master/doc/tpac-2018-slides.pdf) to do something similar.

Please let me know if there's any other cases you're concerned about here that I might've missed!

**Comment by annevk** [comment]
It seems it would include scripts that have `Cross-Origin-Resource-Policy: cross-origin` or `Cross-Origin-Resource-Policy: same-site` as well, no?

Would it not include scripts from documents on other origins, even if the documents are in the same process due to device or platform limitations?

**Comment by acomminos** [comment]
> It seems it would include scripts that have Cross-Origin-Resource-Policy: cross-origin or Cross-Origin-Resource-Policy: same-site as well, no?

It appears I was overzealous with removing the old logic :) Cross-origin scripts are only intended to be exposed in profiles if fetched via CORS (as in some of the old slides from the WG). I'll re-add this check.

> Would it not include scripts from documents on other origins, even if the documents are in the same process due to device or platform limitations?

Correct. Samples are restricted to within the (origin-locked) cluster.

**Comment by annevk** [comment]
Okay, so you can only observe things from other agent clusters through side channels? And, e.g., if they `postMessage()` each other you would just get time gaps in the profile? Which you could also observe using `performance.now()` or equivalent.

**Comment by acomminos** [comment]
> Okay, so you can only observe things from other agent clusters through side channels? And, e.g., if they postMessage() each other you would just get time gaps in the profile? Which you could also observe using performance.now() or equivalent.

Yup, that's indeed the intent (and currently the case in the Blink implementation).

**Comment by acomminos** [comment]
This should be handled more explicitly now by the latest version of the spec, feel free to reopen if there's anything else unclear.
