### ISSUE TITLE
profile() method vs Profiler constructor

### ISSUE THREAD

**Issue by annevk** [WICG/js-self-profiling#47]
Why not use a constructor here?

cc @domenic

**Comment by acomminos** [comment]
`performance.profile()` starts a new profiling session that records samples (in addition to creating an associated Profiler object), which seems quite heavyweight for a constructor IMO. Are there many other constructors in the web platform that are similarly effectful?

**Comment by domenic** [comment]
I mean, `performance.profile()` is still calling that constructor internally and synchronously in C++, right? You're just hiding that constructor from web developers, which is bad practice per https://w3ctag.github.io/design-principles/#constructors ...

**Comment by acomminos** [comment]
Somewhat -- the intent was that the internal `Profiler` constructor does not create a profiling session. `performance.profile()` creates both a `Profiler` and a profiling session, and associates them together. The reason we didn't expose the constructor is because we figured it wouldn't be terribly useful to construct a profiler without a session.

We could do a few things here:

1. Expose a constructor for `Profiler`, and make it start a profiling session as well. Remove `performance.profile()`.
    - The user agent would start recording periodic samples starting at the time of object construction.
    - I was concerned above that this may seem strange to developers, but I'm open to it.
1. Expose a constructor for `Profiler`, and enable starting a profiling session through a new method `Profiler.start()`. Remove `performance.profile()`.
    - Adds a bit of complexity to the API surface -- developers would have to handle more potential profiler states with this approach.
    - Could enable reuse of Profiler objects, but I'm not sure that's necessary or even desirable.
1. Expose a constructor for `Profiler`. It will not have a profiling session associated with it, and only really be suitable for testing/mocking (`performance.profile()` would still be the only way to create a `Profiler` with an attached session).
    - This seems quite unergonomic, I'd worry about this creating further confusion.

Thoughts? At least with the choices here, I lean towards option 1 to retain the simplicity of the "one-shot" profiling session if we're going to expose a constructor.

**Comment by annevk** [comment]
I think 1 is fine, unless there are other uses for this object that requires exposing the different states. (Though we could offer `new Profiler({ disableAutoProfile: true })` for that in the future as well if needed.)
