### ISSUE TITLE
Add row in registry

### ISSUE THREAD

**Issue by npm1** [WICG/js-self-profiling#70]
This specification adds a new PerformanceEntry, so a row should be added in https://w3c.github.io/timing-entrytypes-registry/#registry to specify the buffering behavior of this entry.

**Comment by paulirish** [comment]
> This specification adds a new PerformanceEntry

I'm not seeing a PerformanceEntry mentioned in the spec text. (Or anything that connects the API or [`ProfilerTrace`](https://wicg.github.io/js-self-profiling/#dom-profilertrace) payload to the PerformanceTimeline, etc)

Personally, I've added an `entryType` property onto ProfilerTraces once received so that I can keep all my RUM data together, but distinguished.  But at the same time, having ProfilerTrace subclass PerformanceEntry feels awkward to me.

**Comment by npm1** [comment]
Oh yea I guess this was wrong or the spec changed, I think this can be closed.
